name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH into EC2 and Prepare Target Directory
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo mkdir -p /home/ubuntu/git-CICD/
          sudo chown -R ${{ secrets.EC2_USERNAME }} /home/ubuntu/git-CICD/
          sudo chmod -R 755 /home/ubuntu/git-CICD/

    - name: Copy code to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: ./
        target: /home/ubuntu/git-CICD/

    - name: Install Dependencies
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo pip3 install -r /home/ubuntu/git-CICD/requirements.txt

    - name: Test the code
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        working-directory: /home/ubuntu/git-CICD/
        script: |
          pytest

    - name: Deploy code using Docker image
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        working-directory: /home/ubuntu/git-CICD/
        script: |
          docker build -t simple-web-muzahid:latest .
          docker run -d --name web_flask_app -p 5000:5000 simple-web-muzahid:latest
